### ISSUE TITLE
Unable to recover camera after system crash even with reboot

### ISSUE THREAD

**Issue by marciojersey84** [alliedvision/VimbaPython#138]
I'm using an Allied Vision Alvium 1800 u-500m camera connected to the computer via USB3. When the computer crashes, any subsequent attempts to open the camera either in Vimba Viewer or VimbaPython return a timeout -12 error. The camera is visible but on attempting to open the camera in Vimba Viewer or opening the camera from VimbaPython I get that error. Rebooting the computer doesn't solve the issue. The only option is disconnecting and reconnecting the camera or power cycling the computer. This is a remote computer so these steps are not convenient whenever this happens. The camera has the latest firmware version of 10.0.6C9062B1 and the OS is Ubuntu 20.04. How can I make the camera accessible again?

**Comment by Teresa-AlliedVision** [comment]
Hi,
this is both a known issue, but also one we haven't been able to reproduce. The unfortunate conclusion is, that some USB cards show this issue, but not the ones we have here to test. (We are still working on finding a case for reproduction though). There was one workaround on a customers setup that worked by downgrading the firmware to FW7. If you'd like to try this, please send a support request to support@alliedvision.com **with the serial number of your camera**, so we can send you the firmware.  An older firmware will have less features and will miss some bug fixes, so I would recommend to check the release notes on the firmware, to see if this is an option for you.
https://www.alliedvision.com/en/support/firmware-downloads/
Cheers,
Teresa

**Comment by pgmurphy** [comment]
Hi - have there been any developments with this issue?

**Comment by Teresa-AlliedVision** [comment]
We have seen improvements with the release of firmware 12. Because we weren't able to reproduce and analyze the issue in house, we are relying on customer feedback regarding the improvement.

**Comment by jojje42** [comment]
Same problem(?)!
Firmware 12 on 3 x U-319. Log below is from today. 
Reboot doesn't help. I'm 6h away so I need to call a guy to unplug cams.  This doesn't work at all....

Two cams on this PCI USB card: https://www.startech.com/en-ie/cards-adapters/pexusb3s4v
Third cam on "motherboard" USB (HP Z4 G4 wks) as the PCI USB card couldn't manage it.

```
python3 /opt/vimba/VimbaX_2023-1/api/examples/VmbPy/list_features.py
///////////////////////////////////
/// VmbPy List Features Example ///
///////////////////////////////////

Traceback (most recent call last):
  File "/home/johang/projects/myproj/venv/lib/python3.7/site-packages/vmbpy/camera.py", line 469, in _open
    byref(self._handle))
  File "/home/johang/projects/myproj/venv/lib/python3.7/site-packages/vmbpy/util/tracer.py", line 131, in wrapper
    result = func(*args, **kwargs)
  File "/home/johang/projects/myproj/venv/lib/python3.7/site-packages/vmbpy/c_binding/vmb_c.py", line 891, in call_vmb_c
    getattr(_lib_instance, func_name)(*args)
  File "/home/johang/projects/myproj/venv/lib/python3.7/site-packages/vmbpy/c_binding/vmb_c.py", line 815, in _eval_vmberror
    raise VmbCError(result)
vmbpy.c_binding.vmb_common.VmbCError: VmbCError(<VmbError.Timeout: -12>)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/vimba/VimbaX_2023-1/api/examples/VmbPy/list_features.py", line 188, in <module>
    main()
  File "/opt/vimba/VimbaX_2023-1/api/examples/VmbPy/list_features.py", line 183, in main
    with cam:
  File "/home/johang/projects/myproj/venv/lib/python3.7/site-packages/vmbpy/util/tracer.py", line 131, in wrapper
    result = func(*args, **kwargs)
  File "/home/johang/projects/myproj/venv/lib/python3.7/site-packages/vmbpy/camera.py", line 106, in __enter__
    self._open()
  File "/home/johang/projects/myproj/venv/lib/python3.7/site-packages/vmbpy/util/tracer.py", line 131, in wrapper
    result = func(*args, **kwargs)
  File "/home/johang/projects/myproj/venv/lib/python3.7/site-packages/vmbpy/util/context_decorator.py", line 44, in wrapper
    return func(*args, **kwargs)
  File "/home/johang/projects/myproj/venv/lib/python3.7/site-packages/vmbpy/camera.py", line 494, in _open
    raise exc from e
vmbpy.error.VmbCameraError: <VmbError.Timeout: -12>
```

**Comment by Teresa-AlliedVision** [comment]
Hello, for these issues and in depth troubleshooting, please contact support.
https://www.alliedvision.com/en/about-us/contact-us/technical-support-repair-/-rma/
