### ISSUE TITLE
vmbpy.c_binding.vmb_common.VmbCError: VmbCError(<VmbError.RetriesExceeded: -40>)

### ISSUE THREAD

**Issue by HarshitaKanamadi** [alliedvision/VimbaPython#175]
Traceback (most recent call last):
  File "/app/vimba_client.py", line 75, in _start
    CameraConfigurator.setup(camera, calibration)
  File "/app/camera_configurator.py", line 32, in setup
    camera.load_settings(settings_file, PersistType.All)
  File "/opt/venv/lib/python3.10/site-packages/vmbpy/util/context_decorator.py", line 101, in wrapper
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/vmbpy/util/runtime_type_check.py", line 58, in wrapper
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/vmbpy/featurecontainer.py", line 207, in load_settings
    call_vmb_c('VmbSettingsLoad',
  File "/opt/venv/lib/python3.10/site-packages/vmbpy/util/tracer.py", line 131, in wrapper
    result = func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/vmbpy/c_binding/vmb_c.py", line 891, in call_vmb_c
    getattr(_lib_instance, func_name)(*args)
  File "/opt/venv/lib/python3.10/site-packages/vmbpy/c_binding/vmb_c.py", line 815, in _eval_vmberror
    raise VmbCError(result)
vmbpy.c_binding.vmb_common.VmbCError: VmbCError(<VmbError.RetriesExceeded: -40>)
I am getting this error when i try to load an xml setting file of a camera. When i compared with other setting files, there is no difference i found. Please can anyone help here.

**Comment by Teresa-AlliedVision** [comment]
What is your camera model, firmware and Vimba version?
Does that mean other files work, but this does not? If yes, please upload the files that work and don't work.

**Comment by HarshitaKanamadi** [comment]
Camera Model - GT6400C
Firmware - Prosilica
VimbaX version - 1.0.2
Yes, other files work, the particular xml file with MAC ID: 000F310380BF in the attachment is not working, throws an error. 
Xml file with MAC ID: 000F310380C3 is the one which is working fine.
[xml_config_files.zip](https://github.com/alliedvision/VimbaPython/files/13486427/xml_config_files.zip)
