### ISSUE TITLE
Exception with DiscoveryInterfaceEvent

### ISSUE THREAD

**Issue by jmtatsch** [alliedvision/VimbaPython#177]
Hello,

we run 3 Mako G 319c in an industrial setting and recently noticed the following exception after running the system for 557689 frames:

```
Exception ignored on calling ctypes callback function: <bound method _BaseFeature.__feature_cb_wrapper of Feature(_handle=c_void_p(1),_info=VmbFeatureInfo(name=b'DiscoveryInterfaceEvent',featureDataType=<VmbFeatureData.Enum: 3>,featureFlags= <VmbFeatureFlags.Read: 1> <VmbFeatureFlags.Undocumented: 4>,category=b'/Discovery',displayName=b'Discovery Interface Event',pollingTime=0,unit=None,representation=None,visibility=<VmbFeatureVisibility.Beginner: 1>,tooltip=None,description=b'Indicates the last interface discovery event.',sfncNamespace=b'Custom',isStreamable=False,hasAffectedFeatures=False,hasSelectedFeatures=False))>
Traceback (most recent call last):
File "/home/user/.local/lib/python3.11/site-packages/vimba/feature.py", line 310, in __feature_cb_wrapper
raise e
File "/home/user/.local/lib/python3.11/site-packages/vimba/feature.py", line 302, in __feature_cb_wrapper
handler(self)
File "/home/user/.local/lib/python3.11/site-packages/vimba/vimba.py", line 573, in __inter_cb_wrapper
inter = [i for i in self.__inters if inter_id == i.get_id()].pop()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: pop from empty list
```

What is the cause of this?
Should this maybe be mitigated by checking if the list is empty before popping it?

**Comment by jmtatsch** [comment]
@NiklasKroeger-AlliedVision What is the cause of this?

**Comment by Teresa-AlliedVision** [comment]
Are you using the latest release? Does this error happen when you connect or disconnect a camera?

**Comment by jmtatsch** [comment]
Yes latest release.
We did not wilfully connect/disconnect any cameras.
Maybe a camera resetted itself?

**Comment by jmtatsch** [comment]
@Teresa-AlliedVision any updates on this?

**Comment by jmtatsch** [comment]
@Teresa-AlliedVision @NiklasKroeger-AlliedVision What is going on with customer support?
We have about 25000 € of these cameras installed.
And this seems like a rather simple error to fix.

**Comment by Teresa-AlliedVision** [comment]
For immediate support needs, please contact customer support through us or the distributor if the cameras were bought from.
https://www.alliedvision.com/en/about-us/contact-us/technical-support-repair-/-rma/

**Comment by jmtatsch** [comment]
pinging @Teresa-AlliedVision @NiklasKroeger-AlliedVision
Still no feedback from your support team ONE MONTH AFTER filing the ticket.

**Comment by Teresa-AlliedVision** [comment]
Hi, the ticket got stuck with an invalid status and was not visible in the active ticket queue. Very sorry about that, it has been rectified now.
