### ISSUE TITLE
Transport Layer issues on Raspberry Pi 4

### ISSUE THREAD

**Issue by klastine** [alliedvision/VimbaPython#92]
Hi- I am running Ubuntu 20.04 Desktop (64-bit) on a Raspberry Pi 4, trying to run VimbaPython scripts. I followed the install instructions and ran the Install.sh script in the VimbaUSBTL directory and am able to run the viewer successfully. However, upon running any code that tries to access the cameras, I encounter the following:

``Traceback (most recent call last):
  File "list_cameras.py", line 28, in <module>
    from vimba import *
  File "/usr/local/lib/python3.8/dist-packages/vimba/__init__.py", line 104, in <module>
    from .vimba import Vimba
  File "/usr/local/lib/python3.8/dist-packages/vimba/vimba.py", line 30, in <module>
    from .c_binding import call_vimba_c, VIMBA_C_VERSION, VIMBA_IMAGE_TRANSFORM_VERSION, \
  File "/usr/local/lib/python3.8/dist-packages/vimba/c_binding/__init__.py", line 107, in <module>
    from .vimba_c import VmbInterface, VmbAccessMode, VmbFeatureData, \
  File "/usr/local/lib/python3.8/dist-packages/vimba/c_binding/vimba_c.py", line 674, in <module>
    _lib_instance = _check_version(_attach_signatures(load_vimba_lib('VimbaC')))
  File "/usr/local/lib/python3.8/dist-packages/vimba/c_binding/vimba_common.py", line 484, in load_vimba_lib
    return platform_handlers[sys.platform](vimba_project)
  File "/usr/local/lib/python3.8/dist-packages/vimba/c_binding/vimba_common.py", line 503, in _load_under_linux
    raise VimbaSystemError('No TL detected. Please verify Vimba installation.')
vimba.error.VimbaSystemError: No TL detected. Please verify Vimba installation.``

I double-checked the env variables and ``GENICAM_GENTL64_PATH=:/opt/Vimba_5_1/VimbaUSBTL/CTI/arm_64bit`` is in there. Any help would be greatly appreciated.

**Comment by arunprakash-avt** [comment]
Hi Klastine, after installing the VimbaUSBTL I would like to know if you have logged off the system and logged In?

**Comment by klastine** [comment]
I have shut down the system completely and relaunched it, but not specifically logged out and back in. I have been unable to install QT4, could this be causing such an issue?

**Comment by arunprakash-avt** [comment]
I request you to write us an email to support@alliedvision.com , for our further support purpose.
