### ISSUE TITLE
Timeout error on get_camera

### ISSUE THREAD

**Issue by lpasselin** [alliedvision/VimbaPython#95]
````
Traceback (most recent call last):
  File "/var/home/sico/.local/lib/python3.10/site-packages/vimba/camera.py", line 907, in _open
    call_vimba_c('VmbCameraOpen', self.__info.cameraIdString, self.__access_mode,
  File "/var/home/sico/.local/lib/python3.10/site-packages/vimba/util/tracer.py", line 134, in wrapper
    return func(*args, **kwargs)
  File "/var/home/sico/.local/lib/python3.10/site-packages/vimba/c_binding/vimba_c.py", line 753, in call_vimba_c
    getattr(_lib_instance, func_name)(*args)
  File "/var/home/sico/.local/lib/python3.10/site-packages/vimba/c_binding/vimba_c.py", line 671, in _eval_vmberror
    raise VimbaCError(result)
vimba.c_binding.vimba_common.VimbaCError: VimbaCError(<VmbError.Timeout: -12>)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/home/sico/vimba/Vimba_v5.1_Linux64/Vimba_5_1/VimbaPython/Examples/synchronous_grab.py", line 117, in <module>
    main()
  File "/var/home/sico/vimba/Vimba_v5.1_Linux64/Vimba_5_1/VimbaPython/Examples/synchronous_grab.py", line 108, in main
    with get_camera(cam_id) as cam:
  File "/var/home/sico/.local/lib/python3.10/site-packages/vimba/util/tracer.py", line 134, in wrapper
    return func(*args, **kwargs)
  File "/var/home/sico/.local/lib/python3.10/site-packages/vimba/camera.py", line 362, in __enter__
    self._open()
  File "/var/home/sico/.local/lib/python3.10/site-packages/vimba/util/tracer.py", line 134, in wrapper
    return func(*args, **kwargs)
  File "/var/home/sico/.local/lib/python3.10/site-packages/vimba/util/context_decorator.py", line 44, in wrapper
    return func(*args, **kwargs)
  File "/var/home/sico/.local/lib/python3.10/site-packages/vimba/camera.py", line 924, in _open
    raise exc from e
vimba.error.VimbaCameraError: <VmbError.Timeout: -12>

````

Model is Manta G-1236C.

Initially, the camera was working fine: Ubuntu laptop capturing frames in a docker container.

Now we migrated the system and the docker container runs in a vmware VM with Fedora coreos.

I tested the example scripts provided both in the host coreos and inside the docker container. Both result in the same error.

How can we debug this further? Is there anyway to do it through the python api?

Thank you for your help.

**Comment by lpasselin** [comment]
Closing as this is most likely unrelated to this python wrapper.
